export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const GET_APARTMENTS_REQUEST = 'GET_APARTMENTS_REQUEST';
export const GET_APARTMENT_REQUEST = 'GET_APARTMENT_REQUEST';
export const ADD_APARTMENT_REQUEST = 'ADD_APARTMENT_REQUEST';
export const UPDATE_APARTMENT_REQUEST = 'UPDATE_APARTMENT_REQUEST';
export const DELETE_APARTMENT_REQUEST = 'DELETE_APARTMENT_REQUEST';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
